source 'https://github.com/CocoaPods/Specs.git'

target 'BackgroundUpload-CocoaLumberjack', :exclusive => true do
  pod "BackgroundUpload-CocoaLumberjack", :path => "../"
  pod 'CocoaLumberjack', :git => 'https://github.com/sureshxaton/CocoaLumberjack'
end

target 'Tests', :exclusive => true do
  pod "BackgroundUpload-CocoaLumberjack", :path => "../"
end
